import { CategoryId, ColorId, ProductState, ProductStatus, SearchOrder } from "./dataModels"

interface StringResources {
    readonly email: string,
    readonly password: string,
    readonly signUp: string,
    readonly signIn: string,
    readonly signOut: string,
    readonly newToWebsite: string,
    readonly invalidEmail: string,
    readonly invalidEmailOrPassword: string,
    readonly invalidTelNumber: string,
    readonly shortPasswordError: string,
    readonly signUpError: string,
    readonly telephoneNumber: string,
    readonly username: string,
    readonly personAboutMe: string,
    readonly personFirstName: string,
    readonly personLastName: string,
    readonly personAddress: string,
    readonly textEmptyError: string,
    readonly headerSearchBoxPlaceholder: string,
    readonly search: string,
    readonly specialProducts: string,
    readonly addToCart: string,
    readonly aboutUs: string,
    readonly aboutShopifyDetail: string,
    readonly copyright: string,
    readonly faq: string,
    readonly userAgreement: string,
    readonly cart: string,
    readonly remove: string,
    readonly checkout: string,
    readonly filters: string,
    readonly category: string,
    readonly categories: string,
    readonly price: string,
    readonly color: string,
    readonly colorLabels: Record<ColorId, string>,
    readonly productState: string,
    readonly productStateLabels: Record<ProductState, string>,
    readonly orderBy: string,
    readonly searchOrderLabels: Record<SearchOrder, string>,
    readonly productCountLabel: string,
    readonly allProductsCategory: string,
    readonly productCategoryLabels: Record<CategoryId, string>,
    readonly description: string,
    readonly characteristics: string,
    readonly productComments: string,
    readonly comments: string,
    readonly writeComment: string,
    readonly quantity: string,
    readonly productAlreadyInCart: string,
    readonly uploadImages: string,
    readonly describeProduct: string,
    readonly productTitle: string,
    readonly productTitlePlaceholder: string
    readonly productDescriptionPlaceholder: string,
    readonly selectPlaceholder: string,
    readonly addProduct: string,
    readonly editProduct: string,
    readonly byStatus: string,
    readonly myProductsTitle: string,
    readonly selectAll: string,
    readonly edit: string,
    readonly productStatusLabels: Record<ProductStatus, string>
    readonly delete: string
    readonly myProfile: string,
    readonly myProducts: string,
    readonly myAccount: string,
    readonly myAccountPageDesc: string,
    readonly profileLook: string,
    readonly changePfp: string,
    readonly loginDetails: string,
    readonly changePassword: string,
    readonly personContactDetails: string,
    readonly saveChanges: string,
    readonly postComment: string,
    readonly rateProductHeader: string,
    readonly rateTraderHeader: string
}

export const ukrainianStringResources : StringResources = {
    email: "Email",
    password: "Password",
    signUp: "Реєстарація",
    signIn: "Вхід",
    signOut: "Вийти",
    newToWebsite: "New to website?",
    invalidEmail: "Введіть правильний e-mail",
    invalidEmailOrPassword: "Неправильний email або пароль",
    invalidTelNumber: "Неправильний номер телефону",
    shortPasswordError: "Пароль має не менше 8 символів",
    signUpError: "Виникла помилка при реєстрації",
    username: "Ім'я профілю",
    personAboutMe: "Про мене",
    telephoneNumber: "Номер телефону",
    personFirstName: "Ім'я",
    personLastName: "Прізвище",
    personAddress: "Місто",
    textEmptyError: "Поле не має бути пустим",
    headerSearchBoxPlaceholder: "Я шукаю",
    search: "Пошук",
    specialProducts: "Спеціальні пропозиції",
    addToCart: "Додати у кошик",
    aboutUs: "Про нас",
    aboutShopifyDetail: "Ми заснували Shopify з однією метою: надавати високоякісні, ретельно розроблені продукти, створені для кожного. Наша пристрасть до досконалості рухала нами з самого початку і продовжує рухати нас вперед. Ми знаємо, що кожний товар має значення, і прагнемо зробити Ваші покупки максимально корисними. Не погоджуйтесь ні на що, окрім найкращого",
    copyright: "©2023 від Shopify",
    userAgreement: "Угода користувача",
    faq: "FAQ",
    cart: "Кошик",
    remove: "Видалити",
    checkout: "Оформити замовлення",
    filters: "Фільтри",
    category: "Категорія",
    categories: "Категорії",
    price: "Ціна",
    color: "Колір",
    colorLabels: {
        black: "Чорний",
        white: "Білий",
        cyan: "Голубий",
        red: "Червоний",
        yellow: "Жовтий",
        multicolor: "Різнокольоровий",
    },
    productState: "Стан",
    productStateLabels: {
        acceptable: "Задовільний",
        good: "Хороший",
        "very-good": "Дуже хороший",
        ideal: "Ідеальний",
        new: "Новий",
    },
    orderBy: "Сортувати за",
    searchOrderLabels: {
        "most-expensive": "Найдорожчі",
        "cheapest": "Найдешевші"
    },
    productCountLabel: "Товарів: ",
    allProductsCategory: "Усі товари",
    productCategoryLabels: {
        dress: "Одяг",
        electronics: "Електроніка",
        home: "Товари для дому",
        sport: "Спортивні товари"
    },
    description: "Опис",
    characteristics: "Характеристики",
    productComments: "Відгуки покупців",
    comments: "Відгуки",
    writeComment: "Написати відгук",
    quantity: "Кількість",
    productAlreadyInCart: "Вже в корзині",
    uploadImages: "Завантажте фото",
    describeProduct: "Опишіть вашу річ",
    productTitle: "Назва",
    productTitlePlaceholder: "Наприклад: Супер плаття в горошок Zara",
    productDescriptionPlaceholder: "Приклад: в цій блузці ви будете виглядати як зірка",
    selectPlaceholder: "Виберіть",
    addProduct: "Додати річ",
    editProduct: "Змінити опис",
    myProductsTitle: "Мої речі",
    byStatus: "За статусом",
    selectAll: "Вибрати все",
    edit: "Редагувати",
    productStatusLabels: {
        active: "Активні",
        'on-moderation': "На модерації",
        declined: "Відхилені",
        sold: "Продані"
    },
    delete: "Видалити",
    myProfile: "Мій профіль",
    myProducts: "Мої товари",
    myAccount: "Мій кабінет",
    myAccountPageDesc: "Тут Ви можете переглянути та змінити налаштування свого акаунту",
    profileLook: "Вигляд профілю",
    changePfp: "Змінити зображення профілю",
    loginDetails: "Дані для входу",
    changePassword: "Змінити пароль",
    personContactDetails: "Контактні дані",
    saveChanges: "Зберегти зміни",
    postComment: "Опублікувати",
    rateProductHeader: "Оцініть товар",
    rateTraderHeader: "Оцініть продавця"
}